version: '2'
services:

    # See: docker/Dockerfile
    code_challenge_server:
        build: .

        restart: always

        container_name: docker_code_challenge_server

        environment:
            APACHE_RUN_USER: david
            APACHE_RUN_GROUP: david

        ports:
            - "8080:80"

        volumes:
            - ../.:/var/www/html

        network_mode: "bridge"
